name: integration_tests

on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-20.04 # linux required if you want to use docker
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dri packages
        run: sudo apt-get install -y libxcb-dri3-0 libxcb-dri2-0 mesa-utils libgl1-mesa-glx xvfb
      - name: Build base image
        run: docker build -t mbzirc_sim . -f docker/tests/Dockerfile
      - name: Test using major tag
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./node_modules
          options: -screen 0 1920x1080x24
          run: docker run -v /tmp/.X11-unix:/tmp/.X11-unix \
            mbzirc_sim /bin/bash -c \
              'source /home/$USERNAME/mbzirc_ws/install/setup.bash && \
               colcon test --merge-install \
                           --event-handlers console_direct+ \
                           --packages-select mbzirc_ros && \
               colcon test-result'
